// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfyazbppbknklxmjqxhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmeWF6YnBwYmtua2x4bWpxeGhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTEyNjIsImV4cCI6MjA2NTQ2NzI2Mn0._ICE-spPIbCya9LwaidHXBgjUueT3SpCJQgZ3i0aFEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);